#! /usr/bin/env ruby
require 'time'

if ARGV[0].to_i > 0
	ut = ARGV[0].to_i
else
	puts "usage : utex [unixtime]"
	puts "---------------------------------------------------------"
	ut = Time.now.to_i
end

et_rate = 1440 / 70.0
et = ut * et_rate

et_mm = (et / 2764800 % 12).floor + 1
et_dd = (et / 86400 % 32).floor + 1
et_h = (et / 3600 % 24).floor
et_m = (et / 60 % 60).floor

puts "NORMAL    : "+Time.at(ut).strftime("%Y/%m/%d %H:%M:%S %Z")
puts "UTC       : "+Time.at(ut).gmtime.to_s
puts "RFC2822   : "+Time.at(ut).rfc2822
puts "RFC1123   : "+Time.at(ut).httpdate
puts "ISO8601   : "+Time.at(ut).xmlschema
puts "CTIME     : "+Time.at(ut).ctime
puts "EORZEA    : #{format("%02d",et_mm)}/#{format("%02d",et_dd)} #{format("%02d",et_h)}:#{format("%02d",et_m)}"
